### PR TITLE
2023.06

### PR DESCRIPTION
**Pull request by chrmod**
TODO:
* [x] Remove onboarding extension
* [x] Remove 0035
* [x] Update the theme
* [x] Update locales
* [ ] update feedback url https://www.ghostery.com/support
* [x] replace glowstery with ghosterysearch

### CODE REVIEW

**Comment by GRadziejewski** [comment]
Issue nr 1.

**Description**
After upgrading from the previous version, the language selection is no longer preselected. On the New Tab, certain sentences appear in French, while the browser menu options are displayed in English. When accessing 'about:preferences' and searching for language settings, no language is preselected.

**Precondition**
Check before upgrading, what language is set on the browser.

**Steps to Reproduce**
1. Instal previous version of Ghostery Private Browser
2. Open any few websites
3. Upgrade browser to the newest one
4. Open New Tab and Menu
After upgrade no language_2
5. Open about:preferences
After upgrade no language_1




**Expected results**
"Ghostery: Action required" or any other pop-up should be there until user click any button.


Versions
Browser: Ghostery Private Browser 2023.6 (36875b1)
OS: Windows 10 Pro 19045.2965

**Comment by GRadziejewski** [comment]
Issue nr 2.

**Description**
The main panel of the Ghostery Browser Extension appears empty. This issue is observed both in new installations and when upgrading the extension, resulting in a consistent appearance across both sce

**Steps to Reproduce**
1. Open any few websites with Ghostery Private Browser
2. Open Ghostery main panel
GBE_4
3. Open about:addons
GBE_2
4. Open about:debugging
GBE_3





**Expected results**
Ghostery Browser Extension should be correctly preinstalled.


Versions
Browser: Ghostery Private Browser 2023.6 (36875b1)
OS: Windows 10 Pro 19045.2965

**Comment by GRadziejewski** [comment]
Issue nr 3.

**Description**
Link on the bottom left side of a New Tab is "envoyer des commentaires" and opens https://get.ghosterybrowser.com/feedback which leads at the end to https://ghostery.com

**Steps to Reproduce**
1. Open New Tab
2. Move mouse to left bottom side of the browser and check the link
Feedback or support or get ghostery - opens main page

3. Click on it
https://github.com/ghostery/user-agent-desktop/assets/40433708/b6b83032-9c81-4040-9f7e-e6d2be97a70a






**Expected results**



Versions
Browser: Ghostery Private Browser 2023.6 (36875b1)
OS: Windows 10 Pro 19045.2965

**Comment by GRadziejewski** [comment]
During the tests of (6482aaa)

Fixed: https://github.com/ghostery/user-agent-desktop/pull/646#issuecomment-1623206734

**Comment by GRadziejewski** [comment]
Issue nr 3.

**Description**
I cannot make Ghostery as a default browser. After selecting "Always check if Ghostery is your default browser" on `about:preferences`, there is a prompt with a question but clicking "Set as default browser" button do not triggers anything. 


**Steps to Reproduce**
1. Open about:preferences and click on "Always check if Ghostery is your default browser"
image
2. Click on "Make Default" button - nothing happens
image
3. Reset the browser and wait for the prompt. Click on "Set as default browser" button

https://github.com/ghostery/user-agent-desktop/assets/40433708/0d32a2e0-d72a-4987-a0c5-7eab493905af




**Expected results**
There is a possibility to set Ghostery as a default browser

Versions
Browser: Ghostery Private Browser 2023.6 (6482aaa)
OS: Windows 10 Pro 19045.2965

**Comment by GRadziejewski** [comment]
Issue nr 4.

**Description**
Ghostery Stats are not showing the correct number of blocked and/or modified ads, trackers, saved time. I cannot swipe right or left to see more by clicking the arrow. 


**Steps to Reproduce**
1. Open any website for example https://aarp.org
2. Open Ghostery panel to check how many trackers were blocked or modified
image
3. Open new tab and check the stats
image



**Expected results**
Ghostery Stats must showing the correct numbers  of blocked and/or modified ads, trackers, saved time. And I can swipe left or right to see more. 

Versions
Browser: Ghostery Private Browser 2023.6 (6482aaa)
OS: Windows 10 Pro 19045.2965

**Comment by chrmod** [comment]
@GRadziejewski afaict Issue 4 is not a bug, stats are added only after the page is closed.

**Comment by chrmod** [comment]
Merging for sake of create a nightly.

**Pull request merged**
