### PR TITLE
Hide bookmarks toolbar

### LINKED ISSUE #473: Disable bookmarks toolbar promo
Screenshot 2021-02-02 at 11 20 17

### PR DESCRIPTION
**Pull request by chrmod**
fix #473

### CODE REVIEW

**Comment by chrmod** [comment]
@yokoffing can you please take a look?

**Comment by 2br-2b** [comment]
I tested this, and it works, but it leaves the toolbar hidden even after the user adds a bookmark. Is there a way to make this option toggle if a user adds a bookmark to the bookmarks toolbar?

**Comment by yokoffing** [comment]
@chrmod, please clarify what we want to do with the bookmark toolbar. Are you wanting it not to show by default?

**Comment by 2br-2b** [comment]
I tried on Ghostery, and the bookmark bar shows temporarily, but then will hide again on switching tabs.

**Comment by yokoffing** [comment]
Yes, that sounds like the behavior germane to Firefox at this time.

**Comment by 2br-2b** [comment]
The problem is that this (in my opinion) defeats the purpose of adding a bookmark to the toolbar. If you add a bookmark, then the toolbar should remain showing and should appear on new pages that are opened, rather than closing and disappearing. This way, the user has direct access to the bookmark they just added.

The reason a user adds a bookmark is so that it shows up on the toolbar, and it seems to me that hiding the toolbar defeats the purpose of adding the bookmark.

**Comment by yokoffing** [comment]
@2br-2b Yes, but the behavior you're describing only happens after setting `browser.toolbars.bookmarks.visibility` to `never`; and if a user purposely does that in Firefox, then they didn't want to use the toolbar anyway.

For our purposes (setting defaults for end users), consider two scenarios:
- If default is `newtab` (which is the Firefox default behavior): users have to right-click toolbar > Bookmarks Toolbar > Always Show or Never Show [depending on which behavior they want]
- If default is `never`: users have to right-click > Bookmarks Toolbar > Only show on new tab or Always Show [depending on which behavior they want]

Either way, the user has to right-click and select an option if they want a change. There's no UI in Firefox that hints at this other than leaving `browser.toolbars.bookmarks.visibility` as `newtab`.

@chrmod I'm fine with switching to `never`, but in consideration of less tech-savy users, we may want to leave this as the Firefox default behavior. This way users who _don't_ use this can do what they already do in Firefox now: right-click and select Never Show.

**Comment by 2br-2b** [comment]
I agree, but I think most non tech-savvy users won't know how to right-click > Bookmarks Toolbar > Never Show

**Comment by yokoffing** [comment]
> I agree, but I think most non tech-savvy users won't know how

This is why we should leave this alone IMO — at least for now. We who don't use it know how to quickly disable it.

**Comment by chrmod** [comment]
The `newtab` behavior became default in Firefox 85 https://bugzilla.mozilla.org/show_bug.cgi?id=727668#c51
Previous behavior was `never`. 

IMAO the new tab bar clutters the design. Bookmarking in general is not a very popular user behavior and power users will find their optimal configuration. For less tech-savvy I believe we should offer the simplest (minimal) experience possible. That is why I believe we should not use `newtab` as it's nature as [discussed](https://github.com/ghostery/user-agent-desktop/pull/498#issuecomment-780687442) is not clear.

I will keep the PR open for discussion for next day, if there will no new arguments for keeping new Firefox default, we will revert to `never` in next week release.

**Pull request merged**
