### PR TITLE
Firefox profile migration

### LINKED ISSUE #167: Allow Migrating from Firefox to Ghostery
`browser/components/migration/FirefoxProfileMigrator.jsm` https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/FirefoxProfileMigrator.jsm
I think there is another issue open for this already.

`browser/components/migration/MigrationUtils.jsm` (allow Cliqz to import from Firefox at any point of time, not only on install)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/MigrationUtils.jsm#L458

`browser/components/migration/components.conf`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/components.conf#L35

`browser/components/migration/content/migration.js` (check this file from diff)
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/content/migration.js

`browser/components/migration/content/migration.xhtml`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/content/migration.xhtml

`browser/components/migration/moz.build`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/moz.build

`browser/components/migration/nsIBrowserProfileMigrator.idl`
https://github.com/cliqz-oss/browser-f/blob/master/mozilla-release/browser/components/migration/nsIBrowserProfileMigrator.idl

`browser/locales/en-US/chrome/browser/migration/migration.properties` (settings?)
https://github.com/ghostery/user-agent-desktop/blob/8f59bd745702f7c76f97bc3d67472577824ac644/browser/locales/en-US/chrome/browser/migration/migration.properties

### PR DESCRIPTION
**Pull request by chrmod**
fix #167

The code was copied from the browser-f project.

I've got some errors in browser console while testing it multiple times in a row. Yet I was able to import history, bookmarks and cookies.

### CODE REVIEW

**Comment by chrmod** [comment]
Would be great if someone else could test it locally before merging.

**Comment by sammacbeth** [comment]
This got stuck for me while importing, testing on Linux. Saw this error:
```
JavaScript error: resource:///modules/MigrationUtils.jsm, line 397: Error: TelemetryStopwatch: finishing nonexisting stopwatch. Histogram: "FX_MIGRATION_HISTORY_IMPORT_MS", key: "firefox"
JavaScript error: resource:///modules/FirefoxProfileMigrator.jsm, line 374: TypeError: Cc['@mozilla.org/profile/ff-pass-migrator;1'] is undefined
```

**Comment by chrmod** [comment]
@sammacbeth  regarding the errors in the browser console:
* telemetry one is not a problem as all telemetry is disabled. Also profile migrators (eg. Chrome one) tend to get noisy. I would say we can ignore this problem
* Cliqz Firefox Password migrator was implemented in C++. My suggestion is to avoid using it in this iteration.

**Comment by chrmod** [comment]
@sammacbeth I've fixed the cookie import

**Comment by chrmod** [comment]
Merging this one so we can get feedback on if it is good enougth.

**Comment by sammacbeth** [comment]
Looks like it worked fine for me this time

**Pull request merged**
